# Liveness probe full sample, shell executed
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
  namespace: ben
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy; sleep 600

    # 0:ok, !=0:ko (fail)
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 15
      periodSeconds: 5
    resources:
      limits:
          memory: 20Mi
          cpu: "1"
      requests:
          memory: 20Mi
          cpu: "1"
